### ISSUE TITLE
Grunt version

### ISSUE THREAD

**Issue by DrChills** [RehanSaeed/gulp-minify-cshtml#1]
is there any chance you can release a grunt version for this, or let me know an easy workaround to use with grunt?

fingers crossed, this is the very last piece of my build puzzle!

**Comment by RehanSaeed** [comment]
Wow, the first issue.

Well, this is a super simple Gulp task. It does work but maybe it's too simple. It does not do a lot of things that gulp-minify-html does. The intention was to use it to spur the Microsoft devs into action and give us something that does this, right out of the box in ASP.NET 5.
