### ISSUE TITLE
Invalid syntax concatenating @model with html

### ISSUE THREAD

**Issue by gjsduarte** [RehanSaeed/gulp-minify-cshtml#2]
Hi Rehan,

I've been experimenting with the plugin, and found that the concatenation of the first html line with the Razor view @model declaration creates an invalid syntax.
Have you seen this issue before?

Cheers

**Comment by RehanSaeed** [comment]
We can add an exception for that line. I'll take a look when I get a chance. Would be willing to accept a PR.

**Comment by RehanSaeed** [comment]
I've found some time to look into this issue. I added a `@model` directive to the top of a file and found no issue with the minification. Can you post the code you were trying to minify?

**Comment by RehanSaeed** [comment]
Feel free to reopen.
